import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <>
      <Head>
      <title>Heroflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div className={styles.container}>
  
        <main className={styles.main}>
        <div className={styles.filme}>
          
            <video
              src="/videos/intro1.mp4" width="1200"
              autoPlay 
              preload
              muted>
            </video>
          </div>
          <Link href="./login"> 
            <h1>ENTRAR</h1>
          </Link> 


        </main>

      </div>

    </>
  )
}
