import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import styles from '../styles/Principal.module.css'

export default function Principal() {
  return (
    <>
      <Head>
        <title>Player</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <div className={styles.container}>
      <div className={styles.navbar}>
        <Navbar/>
      </div>

      

        <main className={styles.main}>
          <div className={styles.filme}>
            <video
              src="/videos/adaoNegro.mp4" width="910"
              autoPlay 
              controls
              preload ></video>
          </div>
          
        </main>

        <div className={styles.footer}>
          <Footer/>
        </div>    

    </div>
    </>
  )
}
