import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import React from "react";
import Carrosel from "../components/Slideshow"
import styles from '../styles/Principal.module.css'

export default function Principal() {
  return (
    <>
      <Head>
        <title>Principal</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <div className={styles.container}>
        <div>
          <Navbar />
        </div>


        <div className={styles.mainContent}>

          <main className={styles.main}>
            <div>

            </div>


          </main>
        </div>
        <Carrosel />
        <div>
          <Footer />
        </div>

      </div>
    </>
  )
}
