import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import styles from '../styles/Principal.module.css'

export default function Principal() {
  return (
    <>
      <Head>
        <title>Dragon</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <div className={styles.container}>
      <div className={styles.navbar}>
        <Navbar/>
      </div>

        <header className={styles.header}>
            <Image 
          src="/images/banner.png" 
          width="2000" 
          height="320" 
          alt="banner"/>   
        </header>

        <main className={styles.main}>
          <div className={styles.filme}>
            <video
              src="/video/filme.mp4" width="450" 
              controls
              preload
              poster="/images/thmb01.jpg" ></video>
          </div>
          
        </main>

        <div className={styles.footer}>
          <Footer/>
        </div>    

    </div>
    </>
  )
}
