import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import React from "react";
import Slider from '../components/carousel'
import Slider2 from '../components/carousel'

import styles from '../styles/Principal.module.css'
import { Carousel } from 'react-responsive-carousel';



export default function Principal() {

  const list1 = [
    { link: '/images/wakandaBanner.png', page: '/videos/pantera4.mp4' },
    { link: '/images/adaoBanner.png', page: "./playerCoringa" },
  
    
  ]

  const list2 = [
    { link: '/images/coringa.png', page: '/videos/coringa.mp4' },
    { link: '/images/invasaoSecreta.png', page: '/videos/invasaoSecreta.mp4' },
    { link: '/images/theBatman.png', page: '/videos/theBatman.mp4' },
    { link: '/images/thor4.png', page: '/videos/thor4.mp4' },
    { link: '/images/drEstranho2.png', page: '/videos/doutor2.mp4' },
  ]

  return (
    <>
      <Head>
        <title>Principal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>
        <div>
          <Navbar/>
        </div>

        <div className={styles.mainContent}>
          <main className={styles.main}>
            
            <Slider arquivos={list1} />          
            
            <Slider2 arquivos={list2} />
            

          </main>
        </div>

        <div>
          <Footer/>
        </div>

      </div>
    </>
  )
}
