import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import React from "react";
import Image from 'next/image';
import Slider from '../components/carousel'
import Slider2 from '../components/carousel2'
import Link from 'next/link'
import styles from '../styles/Principal2.module.css'




import { Carousel } from 'react-responsive-carousel';



export default function Principal() {

  const list1 = [
    { link: '/images/wakandaBanner.png', page: '/videos/pantera4.mp4' },

  ]

  const list2 = [
    { link: '/images/coringa.png', page: './playerCoringa' },
    { link: '/images/invasaoSecreta.png', page: './playerIvasaoSecreta' },
    { link: '/images/theBatman.png', page: './playerTheBatman' },
    { link: '/images/thor4.png', page: './playerThor4' },
    { link: '/images/drEstranho2.png', page: 'playerDrEstranho2' },
    { link: '/images/pantera2.png', page: 'playerPantera2' },
  ]

  return (
    <>
      <Head>
        <title>Principal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>
        <div>
          <Navbar />
        </div>
        <div className={styles.destaque}>
          <a>Destaque do Mês</a>
        </div>

        <div className={styles.maindestaque}>
          <Link href="./playerAdao">
            <Image
              src="/images/adaoBanner.png"
              width="3000"
              height="200"
              alt="banner" />
          </Link>
        </div>
        <div className={styles.filmes}>
          <a>Filmes</a>
        </div>
        <div className={styles.mainContent2}>
          <Slider2 arquivos={list2} />
        </div>

        <div>
          <Footer />
        </div>

      </div>
    </>
  )
}
